Feature/company as union entity
TransportSystems2/Backend pull request #142
Opened 2019-03-31 19:56 UTC by fedorkin

2019-04-01 19:38 UTC, MazZilaaaa requested changes

2019-04-01 19:38 UTC, MazZilaaaa commented on Backend/Core/UnitTests.Infrastructure.Business/Organization/CompanyServiceTests.cs
> +        public async Task CreatCompanyWhenNameIsEmptyOrNull()
Ошибка в названии теста. 
Может добавить атрибуты для теста
```
[Theory]
[InlineData("")]
[InlineData(null)]
```
или переименовать имя теста на ```CreateCompanyWhenIsEmpty()```

2019-04-01 19:38 UTC, MazZilaaaa commented on Backend/Application/UnitTests.Business/SignUpServiceTests.cs
>          public async Task SignUpDispatcherDriver()
Тест выше проверят создание компании для водителя. Текущий тест проверяет создание компании для диспетчера. Название текущего теста некорректно.

2019-04-01 19:38 UTC, MazZilaaaa commented on Backend/Core/UnitTests.Infrastructure.Business/Organization/CompanyServiceTests.cs
> +        [Fact]
Ошибка в названии теста.
В тесте проверяется ситуация, когда имя компании пустое, но не проверяется ситуация когда ```var name = null;```
Может добавить атрибуты:
```
[Theory]
[InlineData("")]
[InlineData(null)]
```

Или переименовать название теста в ```CreateCompanyWhenNameIsEmpty()```

2019-04-01 19:38 UTC, MazZilaaaa commented on Backend/Application/UnitTests.Business/Organization/ApplicationCompanyServiceTests.cs
> +
Может стоит проверить вызывается ли метод создания компании у ```DomainCompanyServiceMock```.

2019-04-02 18:56 UTC, fedorkin commented on Backend/Application/UnitTests.Business/Organization/ApplicationCompanyServiceTests.cs
> +
Интересный момент. Сначала я думал, точно также, но потом мне показалось это избыточным. По сути, вызов метода Create уже проверяется в заглушке.
```
Suite.DomainCompanyServiceMock
                .Setup(m => m.Create(domainCompany.Name, domainCompany.IsPrivate))
                .ReturnsAsync(domainCompany); 
```
Если его убрать, то unit test не пройдет. Мало того, если параметры метода будут отличаться от эталонных, unit test тоже провалится. 
Я проверяю вызов метода, только в случае, если он ни как не влияет на результат unit testa. Например, после добавления сущности, надо вызвать Repository.Save(). Вызов этого метода необходим в реальной среде, но на результат unit testa он не оказывает ни какого влияния.

2019-04-02 19:55 UTC, MazZilaaaa approved these changes

2019-04-02 19:55 UTC, merged