Resolved #171
TransportSystems2/Backend pull request #173
Opened 2019-06-05 18:50 UTC by fedorkin

2019-06-06 19:37 UTC, MazZilaaaa requested changes

2019-06-06 19:37 UTC, MazZilaaaa commented on Backend/Application/Business.Tests/ApplicationRouteServiceTests.cs
> +
Не могу понять, для чего необходимо мокать метод 
```csharp
Suite.ServiceMock
.Setup(m => m.GetRouteLeg(It.IsAny<RouteLeg>()))
.ReturnsAsync(new RouteLegAM());
```

2019-06-06 19:37 UTC, MazZilaaaa commented on Backend/Core/Infrastructure.Data.Tests/Billing/BillItemRepositoryTests.cs
> +        public async Task GetAll()
Лишние отступы

2019-06-08 07:27 UTC, TS2Admin approved these changes

2019-06-10 18:52 UTC, TS2Admin approved these changes

2019-06-10 19:19 UTC, MazZilaaaa approved these changes

2019-06-10 19:19 UTC, merged