Feature/get drivers #182
TransportSystems2/Backend pull request #186
Opened 2019-06-30 07:33 UTC by fedorkin

2019-07-05 10:42 UTC, MazZilaaaa requested changes

2019-07-05 10:42 UTC, MazZilaaaa commented on Backend/Application/Business/Organization/ApplicationCompanyService.cs
>          }
В drivers мапятся domainDrivers, но больше нигде не используются. Предлагаю сделать вот так
```csharp
public async Task<ICollection<DriverAM>> GetDrivers(int companyId)
{
    var domainDrivers = await DomainDriverService.GetByCompany(companyId);
	
    return MappingService.Map<IEnumerable<Driver>, ICollection<DriverAM>>(domainDrivers);
}
```

2019-07-05 10:42 UTC, MazZilaaaa commented on Backend/Core/Infrastructure.Http/Users/EmployeeRepository.cs
>          }
Предлагаю сделать вот так. `return Mapper <IEnumerable< UserModel >, ICollection<T>>(users);`

2019-07-07 04:25 UTC, fedorkin commented on Backend/Application/Business/Organization/ApplicationCompanyService.cs
>          }
Done.

2019-07-07 04:25 UTC, fedorkin commented on Backend/Core/Infrastructure.Http/Users/EmployeeRepository.cs
>          }
Done.

2019-07-10 20:10 UTC, MazZilaaaa approved these changes

2019-07-10 20:10 UTC, merged