Feature/get vehicles #183
TransportSystems2/Backend pull request #187
Opened 2019-07-10 19:41 UTC by fedorkin

2019-07-10 20:42 UTC, MazZilaaaa requested changes

2019-07-10 20:42 UTC, MazZilaaaa commented on Backend/Application/Business.Tests/ApplicationVehicleServiceTests.cs
> +        }
Этот тест ведь ничего не тестирует?!

2019-07-10 20:42 UTC, MazZilaaaa commented on Backend/Application/Business/ApplicationVehicleService.cs
> +            return result.ToList();
Не удержался, мощно)

2019-07-10 20:42 UTC, MazZilaaaa commented on Backend/Application/Business/Organization/ApplicationCompanyService.cs
>          }
Странно, для получения водителей используется ApplicationDriverService, а для получения водителей используется доменный VehicleService

2019-07-10 20:42 UTC, MazZilaaaa commented on Backend/Identity/Core/Business/UserService.cs
> +            return result;
Просто предложение. Может сделать асиинхронный foreach?

2019-07-10 20:45 UTC, MazZilaaaa commented on Backend/Application/Business/ApplicationVehicleService.cs
> +            await domainVehicles.ParallelForEachAsync(
Не удержался, мощно)

2019-07-11 03:24 UTC, fedorkin commented on Backend/Identity/Core/Business/UserService.cs
> +            return result;
Identity сервер не может работать с паралленьными запросами в течении одной сессии.
Уже пробовал :)

2019-07-11 05:24 UTC, fedorkin commented on Backend/Application/Business/Organization/ApplicationCompanyService.cs
>          }
Все наоборот. Для получения водителей используется доменный сервис, а для получения транспортных средств - application. Driver и DriverAM - мапятся легко, поля совпадают. В Vehicle не содержится названий характеристик, а только их catalogItemId.  Клиентским приложениям удобно работать уже с разыменованными моделями. Разыменоваваем в ApplciationVehicleService, с привлечением
 ApplicationCatalogService.

2019-07-11 05:24 UTC, fedorkin commented on Backend/Application/Business.Tests/ApplicationVehicleServiceTests.cs
> +        }
Косяк, поправил.

2019-07-11 07:45 UTC, MazZilaaaa approved these changes

2019-07-11 07:45 UTC, merged